# Generated by Django 5.1.2 on 2025-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.TextField(max_length=250)),
                ('receipe_desc', models.TextField()),
                ('receipe_image', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
